### ISSUE TITLE
OCM. folders are created with “/” in the shares

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#10582]
ocis: 6.6.1+6f3322a3d
web: 11.0.1

https://owncloud.dev/ocis/development/testing/#running-test-suite-with-federated-sharing-ocm
Steps: 

- 2 users create connection
- `user1` creates folder `f2` and shares to `user2` with edit role
- `user2` tries to create `new` folder inside the shared folder

Actual: new folder is created with `/`
after reloading the page -> everything is fine. but if the user tries to rename `/folder` -> he gets a 412 error which confuses people

https://github.com/user-attachments/assets/ed78576c-8c4f-4f7c-80c4-7f45d587e4ce

**Comment by rhafer** [comment]
Fixed

**Comment by prashant-gurung899** [comment]
Reopening this issue as the bug is still reproducible.

Infinite Scale 7.0.0+1d6d905ea5 Community
ownCloud Web UI 11.0.6


[Screencast from 27-12-24 11:39:58 पूर्वाह्न +0545.webm](https://github.com/user-attachments/assets/5bf3ddac-9f7b-4dd5-ba09-f37cd58cc4e8)
