### ISSUE TITLE
Stuck on "Redirecting" when using an email address as the username

### ISSUE THREAD

**Issue by mdusher** [owncloud/ocis#2435]
## Describe the bug

When you add a user that has an email address as the "preferred name", you will become stuck on the "Redirecting" page after login as the request to `/ocs/v1.php/v1.php/cloud/users/<username>/groups` fails with a 401 Unauthorized.

It appears that the request fails due to the `@` in the username being URL encoded as `%40` as if you replace the `%40` with `@` and re-run the request it succeeds as expected.

![image](https://user-images.githubusercontent.com/3529874/130755205-e551e9f1-03f7-4935-b4ad-b04261320f7c.png)

## Steps to reproduce

1. Start OCIS with `ocis server`
2. Add a new username where the preferred name is an email address (eg. `ocis accounts add --username michael@example.org --password test123 --preferred-name michael@example.org --mail michael@example.org --displayname Michael --enabled`)
3. Go to your OCIS instance and login as `michael@example.org` with the password `test123`

## Expected behavior
The user is able to login and use OCIS

## Actual behavior
The user is able to login but becomes stuck on the "Redirecting" page.

## Setup

<details>
<p>

Started with:
```console
docker pull owncloud/ocis
docker run --rm -ti -p 9200:9200 owncloud/ocis
```

OCIS Version:
```console
/var/tmp/ocis $ ocis --version
ocis version a150e5f6
```

</p>
</details>

**Comment by jvillafanez** [comment]
The problem seems to be in https://github.com/owncloud/ocis/blob/v1.11.0/ocs/pkg/middleware/requireselforadmin.go#L46
The `URLParam` function returns a "ab%40example.org" userid which doesn't match the username "ab@example.org". This is what causes the 401 error.

This seems to be an issue in go-chi (https://github.com/go-chi/chi/issues/642). Taking this into account and that there are multiple places where we're using this `URLParam` function, I'm not sure if we should try to implement a middleware to adjust the parameters ourselves.
The alternative is to patch all the appearances in order to decode the values properly or provide a function ourselves in case they fix the issue.

**Comment by wkloucek** [comment]
@mdusher this was fixed in https://github.com/cs3org/reva/pull/2076.

Could you please try again with at least oCIS 1.12.0?

**Comment by wkloucek** [comment]
Please reopen if you still have problems with it.

**Comment by mdusher** [comment]
Hi @wkloucek,

I just gave it a go using the `owncloud/ocis:1.12` docker image and it's still giving me the same problem

What I did to test:
```
[mdu@bero ~]$ docker run -ti --rm -p 9200:9200 --name ocis --entrypoint sh owncloud/ocis:1.12
/var/tmp/ocis $ ocis --help | grep -A1 VERSION
VERSION:
   1.12.0

/var/tmp/ocis $ ocis server &
/var/tmp/ocis $ ocis accounts add --username michael@example.org --password test123 --preferred-name michael@example.org --mail michael@example.org --displayname Michael --enabled
```

And I'm still getting a 401 one from the groups endpoint:
![image](https://user-images.githubusercontent.com/3529874/135932694-00fc6d43-5d69-45aa-a769-6994277fa0a6.png)

**Comment by wkloucek** [comment]
Thanks for reproducing. Sorry there was some confusion on my side. It is not fixed in oCIS 1.12.0 but will be in the upcoming oCIS 1.13.0 since https://github.com/cs3org/reva/pull/2076 was merged after the release of oCIS 1.12.0. It is already working on latest master.

Logging in with `michael@example.org` works when starting oCIS like `docker run -ti --rm -p 9200:9200 --name ocis --entrypoint sh owncloud/ocis:latest`.

We expect oCIS 1.13.0 to be released by the end of the week.
