### ISSUE TITLE
Propfind on empty "Share" reports no etag

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/ocis#5591]
```
23-02-16 17:54:42:129 [ info sync.httplogger ]:	"23f27514-5606-45d2-a9e4-20ffbccb137f: Request: PROPFIND https://ocis.owncloud.test/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668/ Header: { Depth: 0, Prefer: return=minimal, Authorization: Bearer [redacted], User-Agent: Mozilla/5.0 (Macintosh) mirall/4.0.0-git (ownCloud, osx-22.2.0 ClientArchitecture: arm64 OsArchitecture: arm64), Accept: */*, Content-Type: text/xml; charset=utf-8, X-Request-ID: 23f27514-5606-45d2-a9e4-20ffbccb137f, Original-Request-ID: 23f27514-5606-45d2-a9e4-20ffbccb137f, Content-Length: 108, } Data: [<?xml version=\"1.0\" encoding=\"utf-8\"?><d:propfind xmlns:d=\"DAV:\"><d:prop><d:getetag/></d:prop></d:propfind>\n]"
23-02-16 17:54:42:146 [ info sync.httplogger ]:	"23f27514-5606-45d2-a9e4-20ffbccb137f: Response: PROPFIND 207 (16ms) https://ocis.owncloud.test/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668/ Header: { Access-Control-Allow-Origin: *, Access-Control-Expose-Headers: Tus-Resumable, Tus-Version, Tus-Extension, Content-Length: 241, Content-Security-Policy: default-src 'none';, Content-Type: application/xml; charset=utf-8, Date: Thu, 16 Feb 2023 16:54:42 GMT, Dav: 1, 3, extended-mkcol, Preference-Applied: return=minimal, Tus-Extension: creation,creation-with-upload,checksum,expiration, Tus-Resumable: 1.0.0, Tus-Version: 1.0.0, Vary: Prefer, X-Content-Type-Options: nosniff, X-Download-Options: noopen, X-Frame-Options: SAMEORIGIN, X-Permitted-Cross-Domain-Policies: none, X-Robots-Tag: none, X-Xss-Protection: 1; mode=block, } Data: [<d:multistatus xmlns:s=\"http://sabredav.org/ns\" xmlns:d=\"DAV:\" xmlns:oc=\"http://owncloud.org/ns\"><d:response><d:href>/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668/</d:href></d:response></d:multistatus>]"

**Comment by michaelstingl** [comment]
@kobergj @rhafer maybe fixed by this PR?
- https://github.com/cs3org/reva/pull/4140

**Comment by Salipa-Gurung** [comment]
PROPFIND to empty shares jail gives the etag (maybe was fixed in https://github.com/cs3org/reva/pull/3681)

```bash
curl -XPROPFIND https://192.168.56.1:9200/dav/spaces/<shares-space-id>/ -uadmin:admin -vk
```
```xml
<d:multistatus
  xmlns:s="http://sabredav.org/ns"
  xmlns:d="DAV:"
  xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668/</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668!a0ca6a90-a365-4782-871e-d44447bbc668</oc:id>
        <oc:fileid>a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668!a0ca6a90-a365-4782-871e-d44447bbc668</oc:fileid>
        <oc:spaceid>a0ca6a90-a365-4782-871e-d44447bbc668</oc:spaceid>
        <oc:shareid></oc:shareid>
        <d:getetag>"DECAFC00FEE"</d:getetag>
        <oc:permissions></oc:permissions>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <oc:size>0</oc:size>
        <oc:favorite>0</oc:favorite>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
    <d:propstat>
      ...
    </d:propstat>
  </d:response>
</d:multistatus>
```

**Comment by TheOneRing** [comment]
Yes, this issue was supposedly fixed. However, I've recently encountered it on https://infinite.owncloud.com/.

**Comment by micbar** [comment]
infinite.owncloud.com runs on 4.0.x, not fixed there.

Would that be a critial backport?

**Comment by TheOneRing** [comment]
Not critical, but it might result in a different polling behaviour.
The change was applied in February and from the pr's activity it looks like at the time there was 3.0 release action.
However, the change only made it to 5.0?
