### ISSUE TITLE
Flaky CI due server panic

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#7518]
related https://github.com/owncloud/ocis/pull/7309

sometimes during the test run server crashes
see log here https://drone.owncloud.com/owncloud/ocis/27811/67/3

we ignore it and restart server using ocis wrapper. As result we have flaky test

example: https://drone.owncloud.com/owncloud/ocis/27811/67/5
![Screenshot 2023-10-17 at 17 43 45](https://github.com/owncloud/ocis/assets/84779829/7c16782f-c62b-4f34-bea1-f8629eeed077)

https://drone.owncloud.com/owncloud/ocis/27812/58/5

**Comment by saw-jan** [comment]
ocis crash log:
```bash
fatal error: concurrent map iteration and map write

goroutine 80969 [running]:
github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3.(*Manager).ListReceivedShares.func2()
	/drone/src/vendor/github.com/cs3org/reva/v2/pkg/share/manager/jsoncs3/jsoncs3.go:865 +0x247
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/drone/src/vendor/golang.org/x/sync/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/drone/src/vendor/golang.org/x/sync/errgroup/errgroup.go:72 +0xa5

goroutine 1 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x7fd46dff48d8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc000731880?, 0xc001839448?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000731880)
	/usr/local/go/src/internal/poll/fd_unix.go:614 +0x2bd
net.(*netFD).accept(0xc000731880)
	/usr/local/go/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc001445290)
	/usr/local/go/src/net/tcpsock_posix.go:148 +0x25
net.(*TCPListener).Accept(0xc001445290)
	/usr/local/go/src/net/tcpsock.go:297 +0x3d
net/http.(*Server).Serve(0xc0002574a0, {0x43d75b0, 0xc001445290})
	/usr/local/go/src/net/http/server.go:3059 +0x385
net/http.Serve(...)
	/usr/local/go/src/net/http/server.go:2581
github.com/owncloud/ocis/v2/ocis/pkg/runtime/service.Start({0xc00109d8c0?, 0x18?, 0x603c0c0?})
	/drone/src/ocis/pkg/runtime/service/service.go:411 +0x8e5
github.com/owncloud/ocis/v2/ocis/pkg/runtime.(*Runtime).Start(0x2bb5560?)
	/drone/src/ocis/pkg/runtime/runtime.go:22 +0x53
github.com/owncloud/ocis/v2/ocis/pkg/command.Server.func2(0xc0010cdce0?)
	/drone/src/ocis/pkg/command/server.go:26 +0x69
github.com/urfave/cli/v2.(*Command).Run(0xc0010cdce0, 0xc001454000, {0xc00061da30, 0x1, 0x1})
	/drone/src/vendor/github.com/urfave/cli/v2/command.go:274 +0x9eb
github.com/urfave/cli/v2.(*Command).Run(0xc001452580, 0xc000d2df40, {0xc000052040, 0x2, 0x2})
	/drone/src/vendor/github.com/urfave/cli/v2/command.go:267 +0xc4d
github.com/urfave/cli/v2.(*App).RunContext(0xc0001fef00, {0x43da5e0?, 0xc0000620b0}, {0xc000052040, 0x2, 0x2})
	/drone/src/vendor/github.com/urfave/cli/v2/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
	/drone/src/vendor/github.com/urfave/cli/v2/app.go:309
github.com/owncloud/ocis/v2/ocis/pkg/command.Execute()
	/drone/src/ocis/pkg/command/root.go:28 +0x17a
main.main()
	/drone/src/ocis/cmd/ocis/main.go:11 +0x19

goroutine 10 [select]:
github.com/patrickmn/go-cache.(*janitor).Run(0xc0001b29f0, 0x0?)
	/drone/src/vendor/github.com/patrickmn/go-cache/cache.go:1079 +0x85
created by github.com/patrickmn/go-cache.runJanitor
	/drone/src/vendor/github.com/patrickmn/go-cache/cache.go:1099 +0xed

goroutine 27 [select, 2 minutes]:
github.com/patrickmn/go-cache.(*janitor).Run(0xc00016b5b0, 0x0?)
	/drone/src/vendor/github.com/patrickmn/go-cache/cache.go:1079 +0x85
created by github.com/patrickmn/go-cache.runJanitor
	/drone/src/vendor/github.com/patrickmn/go-cache/cache.go:1099 +0xed

goroutine 28 [select, 2 minutes]:
go-micro.dev/v4/config/loader/memory.(*watcher).Next(0xc000522ba0)
	/drone/src/vendor/go-micro.dev/v4/config/loader/memory/memory.go:401 +0xb2
go-micro.dev/v4/config.(*config).run.func1({0x43ca060, 0xc000522ba0})
	/drone/src/vendor/go-micro.dev/v4/config/default.go:92 +0x42
go-micro.dev/v4/config.(*config).run(0xc0002663f0)
	/drone/src/vendor/go-micro.dev/v4/config/default.go:133 +0x11b
created by go-micro.dev/v4/config.newConfig
	/drone/src/vendor/go-micro.dev/v4/config/default.go:41 +0x99

goroutine 12 [chan receive, 2 minutes]:
go-micro.dev/v4/config/loader/memory.(*memory).Watch.func1()
	/drone/src/vendor/go-micro.dev/v4/config/loader/memory/memory.go:368 +0x38
created by go-micro.dev/v4/config/loader/memory.(*memory).Watch
	/drone/src/vendor/go-micro.dev/v4/config/loader/memory/memory.go:367 +0x338

goroutine 13 [select, 2 minutes]:
go-micro.dev/v4/config.(*config).run.func2()
	/drone/src/vendor/go-micro.dev/v4/config/default.go:125 +0x65
created by go-micro.dev/v4/config.(*config).run
	/drone/src/vendor/go-micro.dev/v4/config/default.go:124 +0x105

goroutine 14 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000730080)
	/drone/src/vendor/go.opencensus.io/stats/view/worker.go:292 +0xad
created by go.opencensus.io/stats/view.init.0
	/drone/src/vendor/go.opencensus.io/stats/view/worker.go:34 +0x96

goroutine 16 [select, 2 minutes]:
github.com/desertbit/timer.timerRoutine()
	/drone/src/vendor/github.com/desertbit/timer/timers.go:119 +0xba
created by github.com/desertbit/timer.init.0
	/drone/src/vendor/github.com/desertbit/timer/timers.go:15 +0x25
...
```

**Comment by saw-jan** [comment]
Seen in:
- https://drone.owncloud.com/owncloud/ocis/27796/70/3 (PR #7477)

After Merge:
- https://drone.owncloud.com/owncloud/ocis/27811/67/3
- https://drone.owncloud.com/owncloud/ocis/27812/58/3
- https://drone.owncloud.com/owncloud/ocis/27813/69/4
- https://drone.owncloud.com/owncloud/ocis/27816/54/3
- https://drone.owncloud.com/owncloud/ocis/27817/67/3
- https://drone.owncloud.com/owncloud/ocis/27820/67/3
- https://drone.owncloud.com/owncloud/ocis/27822/67/4
- https://drone.owncloud.com/owncloud/ocis/27825/54/3
- https://drone.owncloud.com/owncloud/ocis/27828/71/3

The server side changes in PR #7477 was:
- `FRONTEND_PASSWORD_POLICY_BANNED_PASSWORDS_LIST=banned-password.txt` (`.drone.star`)
- `AutoAcceptShares: true` (`services/frontend/pkg/config/defaults/defaultconfig.go`)

**Comment by ScharfViktor** [comment]
> crash 1
I could reproduce it localy: 

- run test `make test-acceptance-from-core-api TEST_SERVER_URL=https://localhost:9200 TEST_WITH_GRAPH_API=true TEST_OCIS=true BEHAT_FEATURE=tests/acceptance/features/coreApiShareOperationsToShares1/changingFilesShare.feature`
- see server log

Actual: failed step: `When user "Brian" moves file "textfile0.txt" to "/Shares/shared/shared_file.txt" using the WebDAV API` 502 error

**Comment by ScharfViktor** [comment]
> crash 2
fixed here https://github.com/owncloud/ocis/pull/7526

**Comment by kobergj** [comment]
Does that mean all crashes have been fixed now? Or is there still a panic?

**Comment by ScharfViktor** [comment]
> cs3org/reva#4283

this PR bumped reva https://github.com/owncloud/ocis/pull/7581 I guess? 

but panic still exist `Core-API-Tests-ocis-storage-3 -> ocis-server` 
https://drone.owncloud.com/owncloud/ocis/28158/28/3

**Comment by kobergj** [comment]
It is another panic to be precise :smile: https://github.com/cs3org/reva/pull/4290

**Comment by ScharfViktor** [comment]
Checked after https://github.com/owncloud/ocis/pull/7598 ocis bump. No panic :smile: 
@kobergj thank you  :thumbsup:
